import csv
import time
import math
import numpy as np


class FlightLogger:
    def __init__(self, filename="flight_log.csv"):
        self.log_file = open(filename, "w", newline="")
        self.writer = csv.writer(self.log_file)

        self.writer.writerow([
            "t",

            # Actual drone state
            "px", "py", "pz",
            "vx", "vy", "vz",
            "ax", "ay", "az",

            # Commanded attitude/thrust
            "roll_cmd_deg",
            "pitch_cmd_deg",
            "yaw_cmd_deg",
            "thrust_cmd",

            # Planner reference
            "p_ref_x", "p_ref_y", "p_ref_z",
            "v_ref_x", "v_ref_y", "v_ref_z",
            "a_ref_x", "a_ref_y", "a_ref_z",

            # Target gate / waypoint
            "target_x", "target_y", "target_z",

            # Debug info
            "tracking_err_x",
            "tracking_err_y",
            "tracking_err_z",
            "tracking_err_norm",
            "mode",
            "active_gate_idx",
            "loop_dt",
            "replan_requested",
            "replan_duration",
            "hold_command",
            "stale_command_suppressed",
            "plan_mode",
            "plan_start_gate_idx",
            "plan_end_gate_idx",
            "raw_gate_x",
            "raw_gate_y",
            "raw_gate_z",
            "perception_accepted",
            "perception_rejection_reason",
            "last_valid_target_x",
            "last_valid_target_y",
            "last_valid_target_z",
            "target_z_clamped",
            "perception_replan_trigger",
            "distance_to_active_target",
            "gate_completion_triggered",
            "completion_reason",
            "completed_gate_x",
            "completed_gate_y",
            "completed_gate_z",
            "active_gate_idx_before",
            "active_gate_idx_after",
            "race_cursor_before",
            "race_cursor_after",
            "active_target_source",
            "target_rejected_completed",
            "candidate_track_id",
            "candidate_x",
            "candidate_y",
            "candidate_z",
            "candidate_order_score",
            "rejected_wrong_order",
            "rejected_duplicate",
            "rejected_completed_this_lap",
            "race_cursor_advanced",
            "active_gate_idx_advanced",
            "completed_landmark_count",
            "lap_reset_triggered",
            "active_target_cleared",
            "active_target_track_id",
            "active_target_shift_m",
            "active_target_shift_frames",
            "active_target_shift_replan_triggered",
            "active_target_center_at_plan_x",
            "active_target_center_at_plan_y",
            "active_target_center_at_plan_z",
            "active_target_latest_filtered_x",
            "active_target_latest_filtered_y",
            "active_target_latest_filtered_z",
            "target_update_event",
            "target_update_previous_x",
            "target_update_previous_y",
            "target_update_previous_z",
            "target_update_new_x",
            "target_update_new_y",
            "target_update_new_z",
            "target_update_delta_m",
            "target_update_source_track_id",
            "target_update_raw_detection_x",
            "target_update_raw_detection_y",
            "target_update_raw_detection_z",
            "target_update_filtered_track_x",
            "target_update_filtered_track_y",
            "target_update_filtered_track_z",
            "target_update_reason",
            "completed_gate_track_id",
            "yaw_target_source",
            "target_retained_after_completion",
            "next_valid_target_found",
            "valid_candidate_count",
            "approach_vector_x",
            "approach_vector_y",
            "approach_vector_z",
            "gate_progress_along_approach",
            "gate_lateral_error",
            "gate_plane_crossed",
            "near_gate_but_not_crossed",
            "completion_blocked_reason",
            "crossing_true_gate_x",
            "crossing_true_gate_y",
            "crossing_true_gate_z",
            "crossing_vehicle_x",
            "crossing_vehicle_y",
            "crossing_vehicle_z",
            "crossing_error_x",
            "crossing_error_y",
            "crossing_error_z",
            "crossing_lateral_error_xz",
            "no_active_target",
            "no_target_control_mode",
            "hold_anchor_source",
            "hold_anchor_x",
            "hold_anchor_y",
            "hold_anchor_z",
            "velocity_damping_active",
            "completed_gate_reference_blocked",
            "p_ref_source",
            "yaw_hold_value",
            "yaw_hold_value_deg",
            "current_yaw_rad_deg",
            "perception_hold_yaw_deg",
            "telemetry_yaw_deg",
            "previous_yaw_cmd_deg",
            "raw_yaw_cmd_deg",
            "yaw_cmd_after_unwrap_deg",
            "has_commanded_yaw_reference",
            "yaw_rate_limited",
            "post_completion_grace_active",
            "next_track_available_after_completion",
            "skipped_target_clear_after_completion",
            "next_track_after_completion_id",
            "next_target_installed_same_cycle",
            "target_clear_reason",
            "post_completion_grace_suppressed",
            "planning_horizon_track_ids",
            "planning_horizon_waypoint_count",
            "planning_horizon_waypoints",
            "future_track_visible_before_completion",
            "future_track_blocked_reason",
            "horizon_build_cursor",
            "horizon_available_order",
            "horizon_selected_track_ids",
            "horizon_rejected_track_ids",
            "horizon_rejection_reason",
            "planning_lookahead_track_ids",
            "planning_lookahead_source",
            "planning_lookahead_used",
            "tentative_lookahead_used",
            "tentative_lookahead_track_ids",
            "tentative_lookahead_centers",
            "tentative_lookahead_rejection_reason",
            "yolo_detection_count",
            "yolo_detection_confidences",
            "yolo_detection_bboxes",
            "yolo_detection_keypoints",
            "processed_detection_indices",
            "yolo_raw_count",
            "pnp_success_count",
            "world_valid_count",
            "memory_update_count",
            "tentative_track_count",
            "tentative_lookahead_eligible_count",
            "lookahead_pipeline_debug",
            "perception_detection_flow",
            "yolo_confidence",
            "quad_area_px2",
            "old_area_confidence",
            "memory_confidence_used",
            "memory_admission_threshold",
            "memory_admission_passed",
            "planning_cycle_debug",
            "planning_track_horizon_debug",
            "tentative_lookahead_replan_requested",
            "tentative_lookahead_replan_blocked_reason",
            "append_lookahead_called",
            "append_lookahead_input_track_ids",
            "append_lookahead_selected_track_ids",
            "append_lookahead_selected_centers",
            "append_lookahead_selected_types",
            "planning_horizon_waypoint_types",
            "tentative_lookahead_shift_m",
            "tentative_lookahead_shift_track_id",
            "tentative_lookahead_shift_replan_triggered",
            "passthrough_velocity_enabled",
            "passthrough_speed_used",
            "waypoint_velocity_0_x",
            "waypoint_velocity_0_y",
            "waypoint_velocity_0_z",
            "waypoint_velocity_1_x",
            "waypoint_velocity_1_y",
            "waypoint_velocity_1_z",
            "waypoint_velocity_2_x",
            "waypoint_velocity_2_y",
            "waypoint_velocity_2_z",
            "internal_gate_velocity_nonzero",
            "terminal_velocity_mode",
            "replan_reason",
            "no_target_roll_source",
            "no_target_pitch_source",
            "horizontal_hold_disabled_after_completion",
            "track_id",
            "merged_into_track_id",
            "duplicate_merge_reason",
            "race_order_track_ids",
            "race_order_inserted",
            "race_order_rejected_reason",
            "landmark_uncertainty",
            "track_observations",
            "completed_unique_gate_count",
            "active_gate_idx_clamped_by_race_gate_count",
            "suspected_duplicate_track",
            "committed_track_centers",
            "pairwise_committed_track_distances",
            "duplicate_radius_used",
            "merge_candidate_pairs",
            "merge_blocked_reason",
            "rejected_track_temporary_vs_permanent",
            "active_target_admission_status",
            "promoted_lookahead_to_active",
            "promoted_track_id",
            "promoted_track_center_x",
            "promoted_track_center_y",
            "promoted_track_center_z",
            "previous_horizon_track_ids",
            "previous_horizon_waypoint_types",
            "lookahead_promotion_blocked_reason",
            "race_order_after_merge",
            "tentative_track_ids",
            "stable_track_ids",
            "race_admitted_track_ids",
            "current_gate_candidate_track_ids",
            "selected_current_track_id",
            "rejected_current_track_ids",
            "current_selection_rejection_reason",
            "future_lookahead_track_ids",
            "race_order_assignment_debug",
            "selected_next_gate_track_id",
            "selected_next_gate_stability_score",
            "track_hits",
            "track_history_len",
            "track_filtered_x",
            "track_filtered_y",
            "track_filtered_z",
            "track_raw_latest_x",
            "track_raw_latest_y",
            "track_raw_latest_z",
            "track_center_std_x",
            "track_center_std_y",
            "track_center_std_z",
            "track_center_std_norm",
            "track_camera_std_norm",
            "track_reprojection_error_mean",
            "track_reprojection_error_median",
            "track_outlier_count",
            "track_inlier_count",
            "track_is_stable",
            "track_stability_score",
            "promotion_reason",
            "promotion_blocked_reason",
            "selected_target_source",
            "raw_image_corners",
            "ordered_image_corners",
            "pnp_debug_best_ordered_corners",
            "pnp_rvec_x",
            "pnp_rvec_y",
            "pnp_rvec_z",
            "pnp_tvec_x",
            "pnp_tvec_y",
            "pnp_tvec_z",
            "gate_center_camera_x",
            "gate_center_camera_y",
            "gate_center_camera_z",
            "gate_center_body_x",
            "gate_center_body_y",
            "gate_center_body_z",
            "gate_center_world_x",
            "gate_center_world_y",
            "gate_center_world_z",
            "gate_normal_world_x",
            "gate_normal_world_y",
            "gate_normal_world_z",
            "detection_drone_x",
            "detection_drone_y",
            "detection_drone_z",
            "detection_drone_roll_rad",
            "detection_drone_pitch_rad",
            "detection_drone_yaw_rad",
            "detection_drone_yaw_deg",
            "ros_image_stamp_sec",
            "ros_image_stamp_nanosec",
            "image_received_wall_time",
            "image_processed_wall_time",
            "telemetry_position_sample_time",
            "telemetry_attitude_sample_time",
            "image_age_s",
            "attitude_age_s",
            "position_age_s",
            "pose_age_relative_to_image_s",
            "bearing_to_gate_deg",
            "telemetry_yaw_deg_for_image",
            "yaw_error_deg",
            "predicted_quad_offset_from_yaw_px",
            "yaw_pixel_error_px",
            "yaw_image_consistency_status",
            "gazebo_model_x",
            "gazebo_model_y",
            "gazebo_model_z",
            "gazebo_model_yaw_deg",
            "gazebo_camera_x",
            "gazebo_camera_y",
            "gazebo_camera_z",
            "gazebo_camera_yaw_deg",
            "mavsdk_x",
            "mavsdk_y",
            "mavsdk_z",
            "mavsdk_yaw_deg",
            "mavsdk_minus_gazebo_pos_x",
            "mavsdk_minus_gazebo_pos_y",
            "mavsdk_minus_gazebo_pos_z",
            "mavsdk_minus_gazebo_yaw_deg",
            "gazebo_pose_age_s",
            "gate_world_mavsdk_x",
            "gate_world_mavsdk_y",
            "gate_world_mavsdk_z",
            "gate_world_gazebo_x",
            "gate_world_gazebo_y",
            "gate_world_gazebo_z",
            "gate_world_mavsdk_error_to_gt",
            "gate_world_gazebo_error_to_gt",
            "required_yaw_deg_from_pnp_to_gt",
            "mavsdk_yaw_minus_required_deg",
            "gazebo_yaw_minus_required_deg",
            "telemetry_yaw_raw_deg",
            "telemetry_yaw_perception_deg",
            "perception_yaw_correction_deg",
            "gazebo_yaw_deg",
            "expected_planner_yaw_from_gazebo_deg",
            "dynamic_expected_planner_yaw_from_gazebo_deg",
            "raw_yaw_minus_dynamic_gazebo_expected_deg",
            "perception_yaw_minus_dynamic_gazebo_expected_deg",
            "dynamic_correction_deg",
            "use_dynamic_gazebo_perception_yaw_correction",
            "gate_world_uncorrected_x",
            "gate_world_uncorrected_y",
            "gate_world_uncorrected_z",
            "gate_world_corrected_x",
            "gate_world_corrected_y",
            "gate_world_corrected_z",
            "reprojection_error",
            "image_width",
            "image_height",
            "min_corner_x",
            "max_corner_x",
            "min_corner_y",
            "max_corner_y",
            "corner_margin_ok",
            "clipped_detection_rejected",
            "rejected_near_image_edge",
            "track_update_innovation",
            "track_update_accepted",
            "track_center_before_x",
            "track_center_before_y",
            "track_center_before_z",
            "track_center_after_x",
            "track_center_after_y",
            "track_center_after_z",
            "nearest_track_id",
            "nearest_track_distance",
            "nearest_track_hits",
            "nearest_track_committed",
            "nearest_track_stable",
            "association_attempted",
            "association_success",
            "duplicate_rejection_reason",
            "raw_corner_0_x",
            "raw_corner_0_y",
            "raw_corner_1_x",
            "raw_corner_1_y",
            "raw_corner_2_x",
            "raw_corner_2_y",
            "raw_corner_3_x",
            "raw_corner_3_y",
            "ordered_corner_0_x",
            "ordered_corner_0_y",
            "ordered_corner_1_x",
            "ordered_corner_1_y",
            "ordered_corner_2_x",
            "ordered_corner_2_y",
            "ordered_corner_3_x",
            "ordered_corner_3_y",
            "reprojected_corner_0_x",
            "reprojected_corner_0_y",
            "reprojected_corner_1_x",
            "reprojected_corner_1_y",
            "reprojected_corner_2_x",
            "reprojected_corner_2_y",
            "reprojected_corner_3_x",
            "reprojected_corner_3_y",
            "corner_reprojection_error_px",
            "quad_center_x",
            "quad_center_y",
            "image_center_x",
            "image_center_y",
            "quad_center_offset_x",
            "quad_center_offset_y",
            "quad_width_px",
            "quad_height_px",
            "quad_aspect_ratio",
            "quad_area_px",
            "pnp_candidate_count",
            "chosen_pnp_candidate",
            "pnp_candidate_0_error",
            "pnp_candidate_1_error",
            "pnp_selected_order",
            "pnp_selected_solver",
            "pnp_selected_score",
            "pnp_selected_reprojection_error",
            "pnp_selected_gate_center_camera_x",
            "pnp_selected_gate_center_camera_y",
            "pnp_selected_gate_center_camera_z",
            "pnp_selected_reason",
            "pnp_candidate_summary",
            "pnp_candidate_world_summary",
            "pnp_selected_world_score",
            "pnp_selected_world_reason",
            "allow_pnp_corner_reordering",
            "pnp_live_candidate_orders_allowed",
            "pnp_debug_best_order",
            "pnp_live_vs_debug_best_order_mismatch",
            "pnp_lateral_angle",
            "image_center_offset_normalized",
            "keypoint_polygon_signed_area",
            "keypoint_polygon_winding",
            "keypoint_edge_top",
            "keypoint_edge_right",
            "keypoint_edge_bottom",
            "keypoint_edge_left",
            "keypoint_bbox_center_x",
            "keypoint_bbox_center_y",
            "keypoint_polygon_center_x",
            "keypoint_polygon_center_y",
            "keypoint_bbox_polygon_delta_x",
            "keypoint_bbox_polygon_delta_y",
            "raw_keypoint_polygon_signed_area",
            "raw_keypoint_polygon_winding",
            "gate_normal_camera_x",
            "gate_normal_camera_y",
            "gate_normal_camera_z",
            "gate_cam_x",
            "gate_cam_y",
            "gate_cam_z",
            "gate_body_x",
            "gate_body_y",
            "gate_body_z",
            "gate_world_x",
            "gate_world_y",
            "gate_world_z",
            "drone_x_at_detection",
            "drone_y_at_detection",
            "drone_z_at_detection",
            "drone_roll_at_detection_deg",
            "drone_pitch_at_detection_deg",
            "drone_yaw_at_detection_deg",
            "transform_source",
            "perception_transform_mode",
            "camera_to_body_matrix_used",
            "body_to_world_method_used",
            "expected_camera_axis_mode",
            "live_camera_axis_mode_for_expected",
            "expected_uses_live_axis_convention",
            "expected_gate_cam_live_axis_x",
            "expected_gate_cam_live_axis_y",
            "expected_gate_cam_live_axis_z",
            "expected_gate_cam_old_axis_x",
            "expected_gate_cam_old_axis_y",
            "expected_gate_cam_old_axis_z",
            "expected_gate_cam_x",
            "expected_gate_cam_y",
            "expected_gate_cam_z",
            "pnp_camera_x",
            "pnp_camera_y",
            "pnp_camera_z",
            "pnp_gate_cam_x",
            "pnp_gate_cam_y",
            "pnp_gate_cam_z",
            "camera_error_x",
            "camera_error_y",
            "camera_error_z",
            "camera_error_norm",
            "size_depth",
            "size_depth_from_width",
            "size_depth_from_height",
            "pnp_depth_minus_size_depth",
            "expected_gate_projected_center_x",
            "expected_gate_projected_center_y",
            "quad_center_x_for_expected_projection",
            "quad_center_y_for_expected_projection",
            "expected_vs_quad_center_error_px",
            "expected_gate_body_x",
            "expected_gate_body_y",
            "expected_gate_body_z",
            "pnp_gate_body_x",
            "pnp_gate_body_y",
            "pnp_gate_body_z",
            "body_error_x",
            "body_error_y",
            "body_error_z",
            "expected_gate_world_x",
            "expected_gate_world_y",
            "expected_gate_world_z",
            "pnp_gate_world_x",
            "pnp_gate_world_y",
            "pnp_gate_world_z",
            "world_error_x",
            "world_error_y",
            "world_error_z",
            "world_error_norm",
            "debug_expected_gate_idx",
            "live_minus_expected_x",
            "live_minus_expected_y",
            "live_minus_expected_z",
            "live_lateral_error_m",
            "filtered_minus_expected_x",
            "filtered_minus_expected_y",
            "filtered_minus_expected_z",
            "selected_order_vs_axis_mode",
            "live_vs_physical_direct_delta_m",
            "transform_sweep_best_mode",
            "transform_sweep_best_error",
            "transform_sweep_legacy_error",
            "transform_sweep_direct_rad_error",
            "transform_sweep_pi_over_2_minus_yaw_error",
            "transform_sweep_yaw_minus_pi_over_2_error",
            "transform_sweep_neg_yaw_error",
            "transform_sweep_neg_yaw_plus_pi_over_2_error",
            "transform_sweep_legacy_world_x",
            "transform_sweep_legacy_world_y",
            "transform_sweep_legacy_world_z",
            "transform_sweep_direct_rad_world_x",
            "transform_sweep_direct_rad_world_y",
            "transform_sweep_direct_rad_world_z",
            "transform_sweep_yaw_minus_pi_over_2_world_x",
            "transform_sweep_yaw_minus_pi_over_2_world_y",
            "transform_sweep_yaw_minus_pi_over_2_world_z",
            "transform_sweep_pi_over_2_minus_yaw_world_x",
            "transform_sweep_pi_over_2_minus_yaw_world_y",
            "transform_sweep_pi_over_2_minus_yaw_world_z",
            "transform_sweep_physical_direct_rad_world_x",
            "transform_sweep_physical_direct_rad_world_y",
            "transform_sweep_physical_direct_rad_world_z",
            "transform_sweep_best_world_x",
            "transform_sweep_best_world_y",
            "transform_sweep_best_world_z",
            "camera_axis_sweep_best_mode",
            "camera_axis_sweep_best_error",
            "camera_axis_sweep_best_world_x",
            "camera_axis_sweep_best_world_y",
            "camera_axis_sweep_best_world_z",
            "camera_axis_sweep_flu_error",
            "camera_axis_sweep_flu_x_flipped_error",
            "camera_axis_sweep_frd_error",
            "camera_axis_sweep_old_default_error",
            "live_camera_axis_mode",
            "live_camera_axis_det",
            "live_uses_x_mirror",
            "live_vs_camera_axis_x_flipped_delta_m",
            "pnp_camera_x_for_sign",
            "expected_gate_cam_x_for_sign",
            "sign_match_pnp_vs_image",
            "sign_match_expected_vs_image",
            "pnp_size_190_cam_x",
            "pnp_size_190_cam_y",
            "pnp_size_190_cam_z",
            "pnp_size_200_cam_x",
            "pnp_size_200_cam_y",
            "pnp_size_200_cam_z",
            "pnp_size_210_cam_x",
            "pnp_size_210_cam_y",
            "pnp_size_210_cam_z",
            "pnp_size_190_world_x",
            "pnp_size_190_world_y",
            "pnp_size_190_world_z",
            "pnp_size_200_world_x",
            "pnp_size_200_world_y",
            "pnp_size_200_world_z",
            "pnp_size_210_world_x",
            "pnp_size_210_world_y",
            "pnp_size_210_world_z",
            "pnp_size_190_reproj_error",
            "pnp_size_200_reproj_error",
            "pnp_size_210_reproj_error",
            "pnp_size_190_gt_error",
            "pnp_size_200_gt_error",
            "pnp_size_210_gt_error",
            "pnp_solver_used",
            "live_solver_name",
            "live_solver_world_x",
            "live_solver_world_y",
            "live_solver_world_z",
            "live_solver_reproj_error",
            "ippe_world_error_gt",
            "iterative_world_error_gt",
            "pnp_fallback_reason",
            "pnp_best_debug_solver",
            "pnp_best_debug_order",
            "pnp_current_world_error_gt",
            "pnp_best_world_error_gt",
            "pnp_current_cam_x",
            "pnp_current_cam_y",
            "pnp_current_cam_z",
            "pnp_best_cam_x",
            "pnp_best_cam_y",
            "pnp_best_cam_z",
            "pnp_current_world_x",
            "pnp_current_world_y",
            "pnp_current_world_z",
            "pnp_best_world_x",
            "pnp_best_world_y",
            "pnp_best_world_z",
            "pnp_current_reproj_error",
            "pnp_best_reproj_error",
            "pnp_candidate0_world_x",
            "pnp_candidate0_world_y",
            "pnp_candidate0_world_z",
            "pnp_candidate1_world_x",
            "pnp_candidate1_world_y",
            "pnp_candidate1_world_z",
            "pnp_candidate0_error",
            "pnp_candidate1_error",
            "pnp_gt_projected_center_x",
            "pnp_gt_projected_center_y",
            "pnp_gt_projected_quad_center_error_px",
        ])

        self.t0 = time.time()
        self.last_t = None
        self.last_vel = None

    def _vec3(self, value):
        """
        Converts list/tuple/np.array/dict/None into a 3-value numpy vector.
        Returns [nan, nan, nan] if unavailable.
        """
        if value is None:
            return np.array([np.nan, np.nan, np.nan], dtype=float)

        if isinstance(value, dict):
            # Supports {"x":..., "y":..., "z":...}
            if all(k in value for k in ["x", "y", "z"]):
                return np.array([value["x"], value["y"], value["z"]], dtype=float)

            # Supports {"north":..., "east":..., "up":...}
            if all(k in value for k in ["north", "east", "up"]):
                return np.array([value["north"], value["east"], value["up"]], dtype=float)

            return np.array([np.nan, np.nan, np.nan], dtype=float)

        arr = np.array(value, dtype=float).reshape(-1)

        if arr.size >= 3:
            return arr[:3]

        return np.array([np.nan, np.nan, np.nan], dtype=float)

    def _flat_string(self, value):
        if value is None:
            return ""
        arr = np.asarray(value, dtype=float).reshape(-1)
        return " ".join(f"{x:.3f}" for x in arr)

    def _corners4(self, value):
        out = np.full((4, 2), np.nan, dtype=float)
        if value is None:
            return out
        try:
            arr = np.asarray(value, dtype=float).reshape(-1, 2)
        except Exception:
            return out
        n = min(4, arr.shape[0])
        if n > 0:
            out[:n, :] = arr[:n, :]
        return out

    def log(
        self,
        telemetry,
        roll_cmd,
        pitch_cmd,
        yaw_cmd,
        thrust_cmd,
        p_ref=None,
        v_ref=None,
        a_ref=None,
        target=None,
        mode=None,
        active_gate_idx=None,
        loop_dt=np.nan,
        replan_requested=False,
        replan_duration=0.0,
        hold_command=False,
        stale_command_suppressed=False,
        plan_mode=None,
        plan_start_gate_idx=None,
        plan_end_gate_idx=None,
        raw_gate=None,
        perception_accepted=False,
        perception_rejection_reason="",
        last_valid_target=None,
        target_z_clamped=False,
        perception_replan_trigger=False,
        distance_to_active_target=np.nan,
        gate_completion_triggered=False,
        completion_reason="",
        completed_gate_position=None,
        active_gate_idx_before=None,
        active_gate_idx_after=None,
        race_cursor_before=None,
        race_cursor_after=None,
        active_target_source="",
        target_rejected_completed=False,
        candidate_track_id=None,
        candidate_center=None,
        candidate_order_score=np.nan,
        rejected_wrong_order=False,
        rejected_duplicate=False,
        rejected_completed_this_lap=False,
        race_cursor_advanced=False,
        active_gate_idx_advanced=False,
        completed_landmark_count=0,
        lap_reset_triggered=False,
        active_target_cleared=False,
        active_target_track_id=None,
        active_target_shift_m=np.nan,
        active_target_shift_frames=0,
        active_target_shift_replan_triggered=False,
        active_target_center_at_plan=None,
        active_target_latest_filtered_center=None,
        target_update_event=False,
        target_update_previous=None,
        target_update_new=None,
        target_update_delta_m=np.nan,
        target_update_source_track_id=None,
        target_update_raw_detection_center=None,
        target_update_filtered_track_center=None,
        target_update_reason="",
        completed_gate_track_id=None,
        yaw_target_source="",
        target_retained_after_completion=False,
        next_valid_target_found=False,
        valid_candidate_count=0,
        approach_vector=None,
        gate_progress_along_approach=np.nan,
        gate_lateral_error=np.nan,
        gate_plane_crossed=False,
        near_gate_but_not_crossed=False,
        completion_blocked_reason="",
        crossing_true_gate_center=None,
        crossing_vehicle_position=None,
        crossing_error=None,
        crossing_lateral_error_xz=np.nan,
        no_active_target=False,
        no_target_control_mode="",
        hold_anchor_source="",
        hold_anchor=None,
        velocity_damping_active=False,
        completed_gate_reference_blocked=False,
        p_ref_source="",
        yaw_hold_value=np.nan,
        yaw_hold_value_deg=np.nan,
        current_yaw_rad_deg=np.nan,
        perception_hold_yaw_deg=np.nan,
        telemetry_yaw_deg=np.nan,
        previous_yaw_cmd_deg=np.nan,
        raw_yaw_cmd_deg=np.nan,
        yaw_cmd_after_unwrap_deg=np.nan,
        has_commanded_yaw_reference=False,
        yaw_rate_limited=False,
        post_completion_grace_active=False,
        next_track_available_after_completion=False,
        skipped_target_clear_after_completion=False,
        next_track_after_completion_id=None,
        next_target_installed_same_cycle=False,
        target_clear_reason="",
        post_completion_grace_suppressed=False,
        planning_horizon_track_ids=None,
        planning_horizon_waypoint_count=0,
        planning_horizon_waypoints="",
        future_track_visible_before_completion=False,
        future_track_blocked_reason="",
        horizon_build_cursor=0,
        horizon_available_order=None,
        horizon_selected_track_ids=None,
        horizon_rejected_track_ids=None,
        horizon_rejection_reason="",
        planning_lookahead_track_ids=None,
        planning_lookahead_source="",
        planning_lookahead_used=False,
        tentative_lookahead_used=False,
        tentative_lookahead_track_ids=None,
        tentative_lookahead_centers="",
        tentative_lookahead_rejection_reason="",
        yolo_detection_count=0,
        yolo_detection_confidences="",
        yolo_detection_bboxes="",
        yolo_detection_keypoints="",
        processed_detection_indices=None,
        yolo_raw_count=0,
        pnp_success_count=0,
        world_valid_count=0,
        memory_update_count=0,
        tentative_track_count=0,
        tentative_lookahead_eligible_count=0,
        lookahead_pipeline_debug="",
        perception_detection_flow="",
        yolo_confidence="",
        quad_area_px2="",
        old_area_confidence="",
        memory_confidence_used="",
        memory_admission_threshold="",
        memory_admission_passed="",
        planning_cycle_debug="",
        planning_track_horizon_debug="",
        tentative_lookahead_replan_requested=False,
        tentative_lookahead_replan_blocked_reason="",
        append_lookahead_called=False,
        append_lookahead_input_track_ids=None,
        append_lookahead_selected_track_ids=None,
        append_lookahead_selected_centers="",
        append_lookahead_selected_types="",
        planning_horizon_waypoint_types="",
        tentative_lookahead_shift_m=np.nan,
        tentative_lookahead_shift_track_id=None,
        tentative_lookahead_shift_replan_triggered=False,
        passthrough_velocity_enabled=False,
        passthrough_speed_used=np.nan,
        waypoint_velocity_log=None,
        internal_gate_velocity_nonzero=False,
        terminal_velocity_mode="",
        replan_reason="",
        no_target_roll_source="",
        no_target_pitch_source="",
        horizontal_hold_disabled_after_completion=False,
        track_id=None,
        merged_into_track_id=None,
        duplicate_merge_reason="",
        race_order_track_ids=None,
        race_order_inserted=False,
        race_order_rejected_reason="",
        landmark_uncertainty=np.nan,
        track_observations=0,
        completed_unique_gate_count=0,
        active_gate_idx_clamped_by_race_gate_count=False,
        suspected_duplicate_track=False,
        committed_track_centers="",
        pairwise_committed_track_distances="",
        duplicate_radius_used=np.nan,
        merge_candidate_pairs="",
        merge_blocked_reason="",
        rejected_track_temporary_vs_permanent="",
        active_target_admission_status="",
        promoted_lookahead_to_active=False,
        promoted_track_id=None,
        promoted_track_center=None,
        previous_horizon_track_ids=None,
        previous_horizon_waypoint_types="",
        lookahead_promotion_blocked_reason="",
        race_order_after_merge=None,
        tentative_track_ids=None,
        stable_track_ids=None,
        race_admitted_track_ids=None,
        current_gate_candidate_track_ids=None,
        selected_current_track_id=None,
        rejected_current_track_ids=None,
        current_selection_rejection_reason="",
        future_lookahead_track_ids=None,
        race_order_assignment_debug="",
        selected_next_gate_track_id=None,
        selected_next_gate_stability_score=np.nan,
        track_hits=0,
        track_history_len=0,
        track_filtered_center=None,
        track_raw_latest_center=None,
        track_center_std=None,
        track_center_std_norm=np.nan,
        track_camera_std_norm=np.nan,
        track_reprojection_error_mean=np.nan,
        track_reprojection_error_median=np.nan,
        track_outlier_count=0,
        track_inlier_count=0,
        track_is_stable=False,
        track_stability_score=np.nan,
        promotion_reason="",
        promotion_blocked_reason="",
        selected_target_source="",
        raw_image_corners=None,
        ordered_image_corners=None,
        pnp_debug_best_ordered_corners=None,
        pnp_rvec=None,
        pnp_tvec=None,
        gate_center_camera=None,
        gate_center_body=None,
        gate_center_world_debug=None,
        gate_normal_world=None,
        gate_normal_camera=None,
        detection_drone_pose=None,
        detection_drone_yaw_deg=np.nan,
        ros_image_stamp_sec=0,
        ros_image_stamp_nanosec=0,
        image_received_wall_time=np.nan,
        image_processed_wall_time=np.nan,
        telemetry_position_sample_time=np.nan,
        telemetry_attitude_sample_time=np.nan,
        image_age_s=np.nan,
        attitude_age_s=np.nan,
        position_age_s=np.nan,
        pose_age_relative_to_image_s=np.nan,
        bearing_to_gate_deg=np.nan,
        telemetry_yaw_deg_for_image=np.nan,
        yaw_error_deg=np.nan,
        predicted_quad_offset_from_yaw_px=np.nan,
        yaw_pixel_error_px=np.nan,
        yaw_image_consistency_status="",
        gazebo_model_pos=None,
        gazebo_model_yaw_deg=np.nan,
        gazebo_camera_pos=None,
        gazebo_camera_yaw_deg=np.nan,
        mavsdk_pos=None,
        mavsdk_yaw_deg=np.nan,
        mavsdk_minus_gazebo_pos=None,
        mavsdk_minus_gazebo_yaw_deg=np.nan,
        gazebo_pose_age_s=np.nan,
        gate_world_mavsdk=None,
        gate_world_gazebo=None,
        gate_world_mavsdk_error_to_gt=np.nan,
        gate_world_gazebo_error_to_gt=np.nan,
        required_yaw_deg_from_pnp_to_gt=np.nan,
        mavsdk_yaw_minus_required_deg=np.nan,
        gazebo_yaw_minus_required_deg=np.nan,
        telemetry_yaw_raw_deg=np.nan,
        telemetry_yaw_perception_deg=np.nan,
        perception_yaw_correction_deg=np.nan,
        gazebo_yaw_deg=np.nan,
        expected_planner_yaw_from_gazebo_deg=np.nan,
        dynamic_expected_planner_yaw_from_gazebo_deg=np.nan,
        raw_yaw_minus_dynamic_gazebo_expected_deg=np.nan,
        perception_yaw_minus_dynamic_gazebo_expected_deg=np.nan,
        dynamic_correction_deg=np.nan,
        use_dynamic_gazebo_perception_yaw_correction=False,
        gate_world_uncorrected=None,
        gate_world_corrected=None,
        reprojection_error=np.nan,
        reprojected_corners=None,
        corner_reprojection_error_px=np.nan,
        quad_center_x=np.nan,
        quad_center_y=np.nan,
        image_center_x=np.nan,
        image_center_y=np.nan,
        quad_center_offset_x=np.nan,
        quad_center_offset_y=np.nan,
        quad_width_px=np.nan,
        quad_height_px=np.nan,
        quad_aspect_ratio=np.nan,
        quad_area_px=np.nan,
        pnp_candidate_count=0,
        chosen_pnp_candidate=None,
        pnp_candidate_0_error=np.nan,
        pnp_candidate_1_error=np.nan,
        pnp_selected_order="",
        pnp_selected_solver="",
        pnp_selected_score=np.nan,
        pnp_selected_reprojection_error=np.nan,
        pnp_selected_gate_center_camera=None,
        pnp_selected_reason="",
        pnp_candidate_summary="",
        pnp_candidate_world_summary="",
        pnp_selected_world_score=np.nan,
        pnp_selected_world_reason="",
        allow_pnp_corner_reordering=False,
        pnp_live_candidate_orders_allowed="",
        pnp_debug_best_order="",
        pnp_live_vs_debug_best_order_mismatch=False,
        pnp_lateral_angle=np.nan,
        image_center_offset_normalized=np.nan,
        keypoint_polygon_signed_area=np.nan,
        keypoint_polygon_winding="",
        keypoint_edge_top=np.nan,
        keypoint_edge_right=np.nan,
        keypoint_edge_bottom=np.nan,
        keypoint_edge_left=np.nan,
        keypoint_bbox_center=None,
        keypoint_polygon_center=None,
        keypoint_bbox_polygon_delta=None,
        raw_keypoint_polygon_signed_area=np.nan,
        raw_keypoint_polygon_winding="",
        transform_source="",
        perception_transform_mode="",
        camera_to_body_matrix_used=None,
        body_to_world_method_used="",
        expected_camera_axis_mode="",
        live_camera_axis_mode_for_expected="",
        expected_uses_live_axis_convention=False,
        expected_gate_cam_live_axis=None,
        expected_gate_cam_old_axis=None,
        expected_gate_cam=None,
        pnp_camera=None,
        pnp_gate_cam=None,
        camera_error=None,
        camera_error_norm=np.nan,
        size_depth=np.nan,
        size_depth_from_width=np.nan,
        size_depth_from_height=np.nan,
        pnp_depth_minus_size_depth=np.nan,
        expected_gate_projected_center=None,
        expected_vs_quad_center_error_px=np.nan,
        expected_gate_body=None,
        pnp_gate_body=None,
        body_error=None,
        expected_gate_world=None,
        pnp_gate_world=None,
        world_error=None,
        world_error_norm=np.nan,
        debug_expected_gate_idx=-1,
        live_minus_expected=None,
        live_lateral_error_m=np.nan,
        filtered_minus_expected=None,
        selected_order_vs_axis_mode="",
        live_vs_physical_direct_delta_m=np.nan,
        transform_sweep_best_mode="",
        transform_sweep_best_error=np.nan,
        transform_sweep_legacy_error=np.nan,
        transform_sweep_direct_rad_error=np.nan,
        transform_sweep_pi_over_2_minus_yaw_error=np.nan,
        transform_sweep_yaw_minus_pi_over_2_error=np.nan,
        transform_sweep_neg_yaw_error=np.nan,
        transform_sweep_neg_yaw_plus_pi_over_2_error=np.nan,
        transform_sweep_legacy_world=None,
        transform_sweep_direct_rad_world=None,
        transform_sweep_yaw_minus_pi_over_2_world=None,
        transform_sweep_pi_over_2_minus_yaw_world=None,
        transform_sweep_physical_direct_rad_world=None,
        transform_sweep_best_world=None,
        camera_axis_sweep_best_mode="",
        camera_axis_sweep_best_error=np.nan,
        camera_axis_sweep_best_world=None,
        camera_axis_sweep_flu_error=np.nan,
        camera_axis_sweep_flu_x_flipped_error=np.nan,
        camera_axis_sweep_frd_error=np.nan,
        camera_axis_sweep_old_default_error=np.nan,
        live_camera_axis_mode="",
        live_camera_axis_det=np.nan,
        live_uses_x_mirror=False,
        live_vs_camera_axis_x_flipped_delta_m=np.nan,
        sign_match_pnp_vs_image=False,
        sign_match_expected_vs_image=False,
        pnp_size_190_cam=None,
        pnp_size_200_cam=None,
        pnp_size_210_cam=None,
        pnp_size_190_world=None,
        pnp_size_200_world=None,
        pnp_size_210_world=None,
        pnp_size_190_reproj_error=np.nan,
        pnp_size_200_reproj_error=np.nan,
        pnp_size_210_reproj_error=np.nan,
        pnp_size_190_gt_error=np.nan,
        pnp_size_200_gt_error=np.nan,
        pnp_size_210_gt_error=np.nan,
        pnp_solver_used="",
        live_solver_name="",
        live_solver_world=None,
        live_solver_reproj_error=np.nan,
        ippe_world_error_gt=np.nan,
        iterative_world_error_gt=np.nan,
        pnp_fallback_reason="",
        pnp_best_debug_solver="",
        pnp_best_debug_order="",
        pnp_current_world_error_gt=np.nan,
        pnp_best_world_error_gt=np.nan,
        pnp_current_cam=None,
        pnp_best_cam=None,
        pnp_current_world=None,
        pnp_best_world=None,
        pnp_current_reproj_error=np.nan,
        pnp_best_reproj_error=np.nan,
        pnp_candidate0_world=None,
        pnp_candidate1_world=None,
        pnp_candidate0_error=np.nan,
        pnp_candidate1_error=np.nan,
        pnp_gt_projected_center=None,
        pnp_gt_projected_quad_center_error_px=np.nan,
        image_width=0,
        image_height=0,
        min_corner_x=np.nan,
        max_corner_x=np.nan,
        min_corner_y=np.nan,
        max_corner_y=np.nan,
        corner_margin_ok=False,
        clipped_detection_rejected=False,
        rejected_near_image_edge=False,
        track_update_innovation=np.nan,
        track_update_accepted=False,
        track_center_before_update=None,
        track_center_after_update=None,
        nearest_track_id=None,
        nearest_track_distance=np.nan,
        nearest_track_hits=0,
        nearest_track_committed=False,
        nearest_track_stable=False,
        association_attempted=False,
        association_success=False,
        duplicate_rejection_reason="",
    ):
        now = time.time()
        t = now - self.t0

        # Your GetTelemetry seems to store pos/vel as dicts
        pos = self._vec3(getattr(telemetry, "pos", None))
        vel = self._vec3(getattr(telemetry, "vel", None))

        if self.last_t is None or self.last_vel is None:
            acc = np.array([0.0, 0.0, 0.0])
        else:
            dt = now - self.last_t
            acc = (vel - self.last_vel) / dt if dt > 1e-6 else np.zeros(3)

        p_ref = self._vec3(p_ref)
        v_ref = self._vec3(v_ref)
        a_ref = self._vec3(a_ref)
        target = self._vec3(target)
        raw_gate = self._vec3(raw_gate)
        last_valid_target = self._vec3(last_valid_target)
        completed_gate_position = self._vec3(completed_gate_position)
        candidate_center = self._vec3(candidate_center)
        active_target_center_at_plan = self._vec3(active_target_center_at_plan)
        active_target_latest_filtered_center = self._vec3(active_target_latest_filtered_center)
        target_update_previous = self._vec3(target_update_previous)
        target_update_new = self._vec3(target_update_new)
        target_update_raw_detection_center = self._vec3(target_update_raw_detection_center)
        target_update_filtered_track_center = self._vec3(target_update_filtered_track_center)
        crossing_true_gate_center = self._vec3(crossing_true_gate_center)
        crossing_vehicle_position = self._vec3(crossing_vehicle_position)
        crossing_error = self._vec3(crossing_error)
        promoted_track_center = self._vec3(promoted_track_center)
        approach_vector = self._vec3(approach_vector)
        hold_anchor = self._vec3(hold_anchor)
        pnp_rvec = self._vec3(pnp_rvec)
        pnp_tvec = self._vec3(pnp_tvec)
        gate_center_camera = self._vec3(gate_center_camera)
        gate_center_body = self._vec3(gate_center_body)
        gate_center_world_debug = self._vec3(gate_center_world_debug)
        gate_normal_world = self._vec3(gate_normal_world)
        gate_normal_camera = self._vec3(gate_normal_camera)
        track_center_before_update = self._vec3(track_center_before_update)
        track_center_after_update = self._vec3(track_center_after_update)
        track_filtered_center = self._vec3(track_filtered_center)
        track_raw_latest_center = self._vec3(track_raw_latest_center)
        track_center_std = self._vec3(track_center_std)
        expected_gate_cam = self._vec3(expected_gate_cam)
        expected_gate_cam_live_axis = self._vec3(expected_gate_cam_live_axis)
        expected_gate_cam_old_axis = self._vec3(expected_gate_cam_old_axis)
        expected_gate_projected_center = (
            np.asarray(expected_gate_projected_center, dtype=float).reshape(-1)
            if expected_gate_projected_center is not None
            else np.full(2, np.nan)
        )
        if expected_gate_projected_center.size < 2:
            expected_gate_projected_center = np.full(2, np.nan)
        pnp_camera = self._vec3(pnp_camera)
        pnp_gate_cam = self._vec3(pnp_gate_cam)
        camera_error = self._vec3(camera_error)
        expected_gate_body = self._vec3(expected_gate_body)
        pnp_gate_body = self._vec3(pnp_gate_body)
        body_error = self._vec3(body_error)
        expected_gate_world = self._vec3(expected_gate_world)
        pnp_gate_world = self._vec3(pnp_gate_world)
        world_error = self._vec3(world_error)
        live_minus_expected = self._vec3(live_minus_expected)
        filtered_minus_expected = self._vec3(filtered_minus_expected)
        transform_sweep_legacy_world = self._vec3(transform_sweep_legacy_world)
        transform_sweep_direct_rad_world = self._vec3(transform_sweep_direct_rad_world)
        transform_sweep_yaw_minus_pi_over_2_world = self._vec3(transform_sweep_yaw_minus_pi_over_2_world)
        transform_sweep_pi_over_2_minus_yaw_world = self._vec3(transform_sweep_pi_over_2_minus_yaw_world)
        transform_sweep_physical_direct_rad_world = self._vec3(transform_sweep_physical_direct_rad_world)
        transform_sweep_best_world = self._vec3(transform_sweep_best_world)
        camera_axis_sweep_best_world = self._vec3(camera_axis_sweep_best_world)
        pnp_size_190_cam = self._vec3(pnp_size_190_cam)
        pnp_size_200_cam = self._vec3(pnp_size_200_cam)
        pnp_size_210_cam = self._vec3(pnp_size_210_cam)
        pnp_size_190_world = self._vec3(pnp_size_190_world)
        pnp_size_200_world = self._vec3(pnp_size_200_world)
        pnp_size_210_world = self._vec3(pnp_size_210_world)
        live_solver_world = self._vec3(live_solver_world)
        pnp_current_cam = self._vec3(pnp_current_cam)
        pnp_best_cam = self._vec3(pnp_best_cam)
        pnp_current_world = self._vec3(pnp_current_world)
        pnp_best_world = self._vec3(pnp_best_world)
        pnp_candidate0_world = self._vec3(pnp_candidate0_world)
        pnp_candidate1_world = self._vec3(pnp_candidate1_world)
        pnp_selected_gate_center_camera = self._vec3(pnp_selected_gate_center_camera)
        keypoint_bbox_center = np.asarray(keypoint_bbox_center, dtype=float).reshape(-1) if keypoint_bbox_center is not None else np.full(2, np.nan)
        keypoint_polygon_center = np.asarray(keypoint_polygon_center, dtype=float).reshape(-1) if keypoint_polygon_center is not None else np.full(2, np.nan)
        keypoint_bbox_polygon_delta = np.asarray(keypoint_bbox_polygon_delta, dtype=float).reshape(-1) if keypoint_bbox_polygon_delta is not None else np.full(2, np.nan)
        if keypoint_bbox_center.size < 2:
            keypoint_bbox_center = np.full(2, np.nan)
        if keypoint_polygon_center.size < 2:
            keypoint_polygon_center = np.full(2, np.nan)
        if keypoint_bbox_polygon_delta.size < 2:
            keypoint_bbox_polygon_delta = np.full(2, np.nan)
        pnp_gt_projected_center = np.asarray(pnp_gt_projected_center, dtype=float).reshape(-1) if pnp_gt_projected_center is not None else np.full(2, np.nan)
        if pnp_gt_projected_center.size < 2:
            pnp_gt_projected_center = np.full(2, np.nan)
        raw_corners = self._corners4(raw_image_corners)
        ordered_corners = self._corners4(ordered_image_corners)
        reprojected_corners = self._corners4(reprojected_corners)
        detection_pose = np.asarray(detection_drone_pose, dtype=float).reshape(-1) if detection_drone_pose is not None else np.full(6, np.nan)
        gazebo_model_pos = self._vec3(gazebo_model_pos)
        gazebo_camera_pos = self._vec3(gazebo_camera_pos)
        mavsdk_pos = self._vec3(mavsdk_pos)
        mavsdk_minus_gazebo_pos = self._vec3(mavsdk_minus_gazebo_pos)
        gate_world_mavsdk = self._vec3(gate_world_mavsdk)
        gate_world_gazebo = self._vec3(gate_world_gazebo)
        gate_world_uncorrected = self._vec3(gate_world_uncorrected)
        gate_world_corrected = self._vec3(gate_world_corrected)
        if detection_pose.size < 6:
            detection_pose = np.full(6, np.nan)
        chosen_pnp_candidate = -1 if chosen_pnp_candidate is None else chosen_pnp_candidate
        nearest_track_id = -1 if nearest_track_id is None else nearest_track_id
        waypoint_velocity_log = (
            np.asarray(waypoint_velocity_log, dtype=float)
            if waypoint_velocity_log is not None
            else np.full((3, 3), np.nan)
        )
        if waypoint_velocity_log.shape != (3, 3):
            padded = np.full((3, 3), np.nan)
            flat = waypoint_velocity_log.reshape(-1)
            padded.reshape(-1)[:min(9, flat.size)] = flat[:min(9, flat.size)]
            waypoint_velocity_log = padded

        err = p_ref - pos
        err_norm = float(np.linalg.norm(err)) if not np.any(np.isnan(err)) else np.nan

        self.writer.writerow([
            t,

            pos[0], pos[1], pos[2],
            vel[0], vel[1], vel[2],
            acc[0], acc[1], acc[2],

            math.degrees(roll_cmd),
            math.degrees(pitch_cmd),
            math.degrees(yaw_cmd),
            thrust_cmd,

            p_ref[0], p_ref[1], p_ref[2],
            v_ref[0], v_ref[1], v_ref[2],
            a_ref[0], a_ref[1], a_ref[2],

            target[0], target[1], target[2],

            err[0], err[1], err[2],
            err_norm,
            mode,
            active_gate_idx,
            loop_dt,
            bool(replan_requested),
            replan_duration,
            bool(hold_command),
            bool(stale_command_suppressed),
            plan_mode,
            plan_start_gate_idx,
            plan_end_gate_idx,
            raw_gate[0],
            raw_gate[1],
            raw_gate[2],
            bool(perception_accepted),
            perception_rejection_reason,
            last_valid_target[0],
            last_valid_target[1],
            last_valid_target[2],
            bool(target_z_clamped),
            bool(perception_replan_trigger),
            distance_to_active_target,
            bool(gate_completion_triggered),
            completion_reason,
            completed_gate_position[0],
            completed_gate_position[1],
            completed_gate_position[2],
            active_gate_idx_before,
            active_gate_idx_after,
            race_cursor_before,
            race_cursor_after,
            active_target_source,
            bool(target_rejected_completed),
            candidate_track_id,
            candidate_center[0],
            candidate_center[1],
            candidate_center[2],
            candidate_order_score,
            bool(rejected_wrong_order),
            bool(rejected_duplicate),
            bool(rejected_completed_this_lap),
            bool(race_cursor_advanced),
            bool(active_gate_idx_advanced),
            completed_landmark_count,
            bool(lap_reset_triggered),
            bool(active_target_cleared),
            active_target_track_id,
            active_target_shift_m,
            active_target_shift_frames,
            bool(active_target_shift_replan_triggered),
            active_target_center_at_plan[0],
            active_target_center_at_plan[1],
            active_target_center_at_plan[2],
            active_target_latest_filtered_center[0],
            active_target_latest_filtered_center[1],
            active_target_latest_filtered_center[2],
            bool(target_update_event),
            target_update_previous[0],
            target_update_previous[1],
            target_update_previous[2],
            target_update_new[0],
            target_update_new[1],
            target_update_new[2],
            target_update_delta_m,
            target_update_source_track_id,
            target_update_raw_detection_center[0],
            target_update_raw_detection_center[1],
            target_update_raw_detection_center[2],
            target_update_filtered_track_center[0],
            target_update_filtered_track_center[1],
            target_update_filtered_track_center[2],
            target_update_reason,
            completed_gate_track_id,
            yaw_target_source,
            bool(target_retained_after_completion),
            bool(next_valid_target_found),
            valid_candidate_count,
            approach_vector[0],
            approach_vector[1],
            approach_vector[2],
            gate_progress_along_approach,
            gate_lateral_error,
            bool(gate_plane_crossed),
            bool(near_gate_but_not_crossed),
            completion_blocked_reason,
            crossing_true_gate_center[0],
            crossing_true_gate_center[1],
            crossing_true_gate_center[2],
            crossing_vehicle_position[0],
            crossing_vehicle_position[1],
            crossing_vehicle_position[2],
            crossing_error[0],
            crossing_error[1],
            crossing_error[2],
            crossing_lateral_error_xz,
            bool(no_active_target),
            no_target_control_mode,
            hold_anchor_source,
            hold_anchor[0],
            hold_anchor[1],
            hold_anchor[2],
            bool(velocity_damping_active),
            bool(completed_gate_reference_blocked),
            p_ref_source,
            yaw_hold_value,
            yaw_hold_value_deg,
            current_yaw_rad_deg,
            perception_hold_yaw_deg,
            telemetry_yaw_deg,
            previous_yaw_cmd_deg,
            raw_yaw_cmd_deg,
            yaw_cmd_after_unwrap_deg,
            bool(has_commanded_yaw_reference),
            bool(yaw_rate_limited),
            bool(post_completion_grace_active),
            bool(next_track_available_after_completion),
            bool(skipped_target_clear_after_completion),
            next_track_after_completion_id,
            bool(next_target_installed_same_cycle),
            target_clear_reason,
            bool(post_completion_grace_suppressed),
            "" if planning_horizon_track_ids is None else " ".join(str(x) for x in planning_horizon_track_ids),
            planning_horizon_waypoint_count,
            planning_horizon_waypoints,
            bool(future_track_visible_before_completion),
            future_track_blocked_reason,
            horizon_build_cursor,
            "" if horizon_available_order is None else " ".join(str(x) for x in horizon_available_order),
            "" if horizon_selected_track_ids is None else " ".join(str(x) for x in horizon_selected_track_ids),
            "" if horizon_rejected_track_ids is None else " ".join(str(x) for x in horizon_rejected_track_ids),
            horizon_rejection_reason,
            "" if planning_lookahead_track_ids is None else " ".join(str(x) for x in planning_lookahead_track_ids),
            planning_lookahead_source,
            bool(planning_lookahead_used),
            bool(tentative_lookahead_used),
            "" if tentative_lookahead_track_ids is None else " ".join(str(x) for x in tentative_lookahead_track_ids),
            tentative_lookahead_centers,
            tentative_lookahead_rejection_reason,
            yolo_detection_count,
            yolo_detection_confidences,
            yolo_detection_bboxes,
            yolo_detection_keypoints,
            "" if processed_detection_indices is None else " ".join(str(x) for x in processed_detection_indices),
            yolo_raw_count,
            pnp_success_count,
            world_valid_count,
            memory_update_count,
            tentative_track_count,
            tentative_lookahead_eligible_count,
            lookahead_pipeline_debug,
            perception_detection_flow,
            yolo_confidence,
            quad_area_px2,
            old_area_confidence,
            memory_confidence_used,
            memory_admission_threshold,
            memory_admission_passed,
            planning_cycle_debug,
            planning_track_horizon_debug,
            bool(tentative_lookahead_replan_requested),
            tentative_lookahead_replan_blocked_reason,
            bool(append_lookahead_called),
            "" if append_lookahead_input_track_ids is None else " ".join(str(x) for x in append_lookahead_input_track_ids),
            "" if append_lookahead_selected_track_ids is None else " ".join(str(x) for x in append_lookahead_selected_track_ids),
            append_lookahead_selected_centers,
            append_lookahead_selected_types,
            planning_horizon_waypoint_types,
            tentative_lookahead_shift_m,
            tentative_lookahead_shift_track_id,
            bool(tentative_lookahead_shift_replan_triggered),
            bool(passthrough_velocity_enabled),
            passthrough_speed_used,
            waypoint_velocity_log[0, 0],
            waypoint_velocity_log[0, 1],
            waypoint_velocity_log[0, 2],
            waypoint_velocity_log[1, 0],
            waypoint_velocity_log[1, 1],
            waypoint_velocity_log[1, 2],
            waypoint_velocity_log[2, 0],
            waypoint_velocity_log[2, 1],
            waypoint_velocity_log[2, 2],
            bool(internal_gate_velocity_nonzero),
            terminal_velocity_mode,
            replan_reason,
            no_target_roll_source,
            no_target_pitch_source,
            bool(horizontal_hold_disabled_after_completion),
            track_id,
            merged_into_track_id,
            duplicate_merge_reason,
            "" if race_order_track_ids is None else " ".join(str(x) for x in race_order_track_ids),
            bool(race_order_inserted),
            race_order_rejected_reason,
            landmark_uncertainty,
            track_observations,
            completed_unique_gate_count,
            bool(active_gate_idx_clamped_by_race_gate_count),
            bool(suspected_duplicate_track),
            committed_track_centers,
            pairwise_committed_track_distances,
            duplicate_radius_used,
            merge_candidate_pairs,
            merge_blocked_reason,
            rejected_track_temporary_vs_permanent,
            active_target_admission_status,
            bool(promoted_lookahead_to_active),
            promoted_track_id,
            promoted_track_center[0],
            promoted_track_center[1],
            promoted_track_center[2],
            "" if previous_horizon_track_ids is None else " ".join(str(x) for x in previous_horizon_track_ids),
            previous_horizon_waypoint_types,
            lookahead_promotion_blocked_reason,
            "" if race_order_after_merge is None else " ".join(str(x) for x in race_order_after_merge),
            "" if tentative_track_ids is None else " ".join(str(x) for x in tentative_track_ids),
            "" if stable_track_ids is None else " ".join(str(x) for x in stable_track_ids),
            "" if race_admitted_track_ids is None else " ".join(str(x) for x in race_admitted_track_ids),
            "" if current_gate_candidate_track_ids is None else " ".join(str(x) for x in current_gate_candidate_track_ids),
            selected_current_track_id,
            "" if rejected_current_track_ids is None else " ".join(str(x) for x in rejected_current_track_ids),
            current_selection_rejection_reason,
            "" if future_lookahead_track_ids is None else " ".join(str(x) for x in future_lookahead_track_ids),
            race_order_assignment_debug,
            selected_next_gate_track_id,
            selected_next_gate_stability_score,
            track_hits,
            track_history_len,
            track_filtered_center[0],
            track_filtered_center[1],
            track_filtered_center[2],
            track_raw_latest_center[0],
            track_raw_latest_center[1],
            track_raw_latest_center[2],
            track_center_std[0],
            track_center_std[1],
            track_center_std[2],
            track_center_std_norm,
            track_camera_std_norm,
            track_reprojection_error_mean,
            track_reprojection_error_median,
            track_outlier_count,
            track_inlier_count,
            bool(track_is_stable),
            track_stability_score,
            promotion_reason,
            promotion_blocked_reason,
            selected_target_source,
            self._flat_string(raw_image_corners),
            self._flat_string(ordered_image_corners),
            self._flat_string(pnp_debug_best_ordered_corners),
            pnp_rvec[0],
            pnp_rvec[1],
            pnp_rvec[2],
            pnp_tvec[0],
            pnp_tvec[1],
            pnp_tvec[2],
            gate_center_camera[0],
            gate_center_camera[1],
            gate_center_camera[2],
            gate_center_body[0],
            gate_center_body[1],
            gate_center_body[2],
            gate_center_world_debug[0],
            gate_center_world_debug[1],
            gate_center_world_debug[2],
            gate_normal_world[0],
            gate_normal_world[1],
            gate_normal_world[2],
            detection_pose[0],
            detection_pose[1],
            detection_pose[2],
            detection_pose[3],
            detection_pose[4],
            detection_pose[5],
            detection_drone_yaw_deg,
            ros_image_stamp_sec,
            ros_image_stamp_nanosec,
            image_received_wall_time,
            image_processed_wall_time,
            telemetry_position_sample_time,
            telemetry_attitude_sample_time,
            image_age_s,
            attitude_age_s,
            position_age_s,
            pose_age_relative_to_image_s,
            bearing_to_gate_deg,
            telemetry_yaw_deg_for_image,
            yaw_error_deg,
            predicted_quad_offset_from_yaw_px,
            yaw_pixel_error_px,
            yaw_image_consistency_status,
            gazebo_model_pos[0],
            gazebo_model_pos[1],
            gazebo_model_pos[2],
            gazebo_model_yaw_deg,
            gazebo_camera_pos[0],
            gazebo_camera_pos[1],
            gazebo_camera_pos[2],
            gazebo_camera_yaw_deg,
            mavsdk_pos[0],
            mavsdk_pos[1],
            mavsdk_pos[2],
            mavsdk_yaw_deg,
            mavsdk_minus_gazebo_pos[0],
            mavsdk_minus_gazebo_pos[1],
            mavsdk_minus_gazebo_pos[2],
            mavsdk_minus_gazebo_yaw_deg,
            gazebo_pose_age_s,
            gate_world_mavsdk[0],
            gate_world_mavsdk[1],
            gate_world_mavsdk[2],
            gate_world_gazebo[0],
            gate_world_gazebo[1],
            gate_world_gazebo[2],
            gate_world_mavsdk_error_to_gt,
            gate_world_gazebo_error_to_gt,
            required_yaw_deg_from_pnp_to_gt,
            mavsdk_yaw_minus_required_deg,
            gazebo_yaw_minus_required_deg,
            telemetry_yaw_raw_deg,
            telemetry_yaw_perception_deg,
            perception_yaw_correction_deg,
            gazebo_yaw_deg,
            expected_planner_yaw_from_gazebo_deg,
            dynamic_expected_planner_yaw_from_gazebo_deg,
            raw_yaw_minus_dynamic_gazebo_expected_deg,
            perception_yaw_minus_dynamic_gazebo_expected_deg,
            dynamic_correction_deg,
            bool(use_dynamic_gazebo_perception_yaw_correction),
            gate_world_uncorrected[0],
            gate_world_uncorrected[1],
            gate_world_uncorrected[2],
            gate_world_corrected[0],
            gate_world_corrected[1],
            gate_world_corrected[2],
            reprojection_error,
            image_width,
            image_height,
            min_corner_x,
            max_corner_x,
            min_corner_y,
            max_corner_y,
            bool(corner_margin_ok),
            bool(clipped_detection_rejected),
            bool(rejected_near_image_edge),
            track_update_innovation,
            bool(track_update_accepted),
            track_center_before_update[0],
            track_center_before_update[1],
            track_center_before_update[2],
            track_center_after_update[0],
            track_center_after_update[1],
            track_center_after_update[2],
            nearest_track_id,
            nearest_track_distance,
            nearest_track_hits,
            bool(nearest_track_committed),
            bool(nearest_track_stable),
            bool(association_attempted),
            bool(association_success),
            duplicate_rejection_reason,
            raw_corners[0, 0],
            raw_corners[0, 1],
            raw_corners[1, 0],
            raw_corners[1, 1],
            raw_corners[2, 0],
            raw_corners[2, 1],
            raw_corners[3, 0],
            raw_corners[3, 1],
            ordered_corners[0, 0],
            ordered_corners[0, 1],
            ordered_corners[1, 0],
            ordered_corners[1, 1],
            ordered_corners[2, 0],
            ordered_corners[2, 1],
            ordered_corners[3, 0],
            ordered_corners[3, 1],
            reprojected_corners[0, 0],
            reprojected_corners[0, 1],
            reprojected_corners[1, 0],
            reprojected_corners[1, 1],
            reprojected_corners[2, 0],
            reprojected_corners[2, 1],
            reprojected_corners[3, 0],
            reprojected_corners[3, 1],
            corner_reprojection_error_px,
            quad_center_x,
            quad_center_y,
            image_center_x,
            image_center_y,
            quad_center_offset_x,
            quad_center_offset_y,
            quad_width_px,
            quad_height_px,
            quad_aspect_ratio,
            quad_area_px,
            pnp_candidate_count,
            chosen_pnp_candidate,
            pnp_candidate_0_error,
            pnp_candidate_1_error,
            pnp_selected_order,
            pnp_selected_solver,
            pnp_selected_score,
            pnp_selected_reprojection_error,
            pnp_selected_gate_center_camera[0],
            pnp_selected_gate_center_camera[1],
            pnp_selected_gate_center_camera[2],
            pnp_selected_reason,
            pnp_candidate_summary,
            pnp_candidate_world_summary,
            pnp_selected_world_score,
            pnp_selected_world_reason,
            allow_pnp_corner_reordering,
            pnp_live_candidate_orders_allowed,
            pnp_debug_best_order,
            pnp_live_vs_debug_best_order_mismatch,
            pnp_lateral_angle,
            image_center_offset_normalized,
            keypoint_polygon_signed_area,
            keypoint_polygon_winding,
            keypoint_edge_top,
            keypoint_edge_right,
            keypoint_edge_bottom,
            keypoint_edge_left,
            keypoint_bbox_center[0],
            keypoint_bbox_center[1],
            keypoint_polygon_center[0],
            keypoint_polygon_center[1],
            keypoint_bbox_polygon_delta[0],
            keypoint_bbox_polygon_delta[1],
            raw_keypoint_polygon_signed_area,
            raw_keypoint_polygon_winding,
            gate_normal_camera[0],
            gate_normal_camera[1],
            gate_normal_camera[2],
            gate_center_camera[0],
            gate_center_camera[1],
            gate_center_camera[2],
            gate_center_body[0],
            gate_center_body[1],
            gate_center_body[2],
            gate_center_world_debug[0],
            gate_center_world_debug[1],
            gate_center_world_debug[2],
            detection_pose[0],
            detection_pose[1],
            detection_pose[2],
            math.degrees(detection_pose[3]),
            math.degrees(detection_pose[4]),
            math.degrees(detection_pose[5]),
            transform_source,
            perception_transform_mode,
            self._flat_string(camera_to_body_matrix_used),
            body_to_world_method_used,
            expected_camera_axis_mode,
            live_camera_axis_mode_for_expected,
            bool(expected_uses_live_axis_convention),
            expected_gate_cam_live_axis[0],
            expected_gate_cam_live_axis[1],
            expected_gate_cam_live_axis[2],
            expected_gate_cam_old_axis[0],
            expected_gate_cam_old_axis[1],
            expected_gate_cam_old_axis[2],
            expected_gate_cam[0],
            expected_gate_cam[1],
            expected_gate_cam[2],
            pnp_camera[0],
            pnp_camera[1],
            pnp_camera[2],
            pnp_gate_cam[0],
            pnp_gate_cam[1],
            pnp_gate_cam[2],
            camera_error[0],
            camera_error[1],
            camera_error[2],
            camera_error_norm,
            size_depth,
            size_depth_from_width,
            size_depth_from_height,
            pnp_depth_minus_size_depth,
            expected_gate_projected_center[0],
            expected_gate_projected_center[1],
            quad_center_x,
            quad_center_y,
            expected_vs_quad_center_error_px,
            expected_gate_body[0],
            expected_gate_body[1],
            expected_gate_body[2],
            pnp_gate_body[0],
            pnp_gate_body[1],
            pnp_gate_body[2],
            body_error[0],
            body_error[1],
            body_error[2],
            expected_gate_world[0],
            expected_gate_world[1],
            expected_gate_world[2],
            pnp_gate_world[0],
            pnp_gate_world[1],
            pnp_gate_world[2],
            world_error[0],
            world_error[1],
            world_error[2],
            world_error_norm,
            debug_expected_gate_idx,
            live_minus_expected[0],
            live_minus_expected[1],
            live_minus_expected[2],
            live_lateral_error_m,
            filtered_minus_expected[0],
            filtered_minus_expected[1],
            filtered_minus_expected[2],
            selected_order_vs_axis_mode,
            live_vs_physical_direct_delta_m,
            transform_sweep_best_mode,
            transform_sweep_best_error,
            transform_sweep_legacy_error,
            transform_sweep_direct_rad_error,
            transform_sweep_pi_over_2_minus_yaw_error,
            transform_sweep_yaw_minus_pi_over_2_error,
            transform_sweep_neg_yaw_error,
            transform_sweep_neg_yaw_plus_pi_over_2_error,
            transform_sweep_legacy_world[0],
            transform_sweep_legacy_world[1],
            transform_sweep_legacy_world[2],
            transform_sweep_direct_rad_world[0],
            transform_sweep_direct_rad_world[1],
            transform_sweep_direct_rad_world[2],
            transform_sweep_yaw_minus_pi_over_2_world[0],
            transform_sweep_yaw_minus_pi_over_2_world[1],
            transform_sweep_yaw_minus_pi_over_2_world[2],
            transform_sweep_pi_over_2_minus_yaw_world[0],
            transform_sweep_pi_over_2_minus_yaw_world[1],
            transform_sweep_pi_over_2_minus_yaw_world[2],
            transform_sweep_physical_direct_rad_world[0],
            transform_sweep_physical_direct_rad_world[1],
            transform_sweep_physical_direct_rad_world[2],
            transform_sweep_best_world[0],
            transform_sweep_best_world[1],
            transform_sweep_best_world[2],
            camera_axis_sweep_best_mode,
            camera_axis_sweep_best_error,
            camera_axis_sweep_best_world[0],
            camera_axis_sweep_best_world[1],
            camera_axis_sweep_best_world[2],
            camera_axis_sweep_flu_error,
            camera_axis_sweep_flu_x_flipped_error,
            camera_axis_sweep_frd_error,
            camera_axis_sweep_old_default_error,
            live_camera_axis_mode,
            live_camera_axis_det,
            bool(live_uses_x_mirror),
            live_vs_camera_axis_x_flipped_delta_m,
            pnp_gate_cam[0],
            expected_gate_cam[0],
            bool(sign_match_pnp_vs_image),
            bool(sign_match_expected_vs_image),
            pnp_size_190_cam[0],
            pnp_size_190_cam[1],
            pnp_size_190_cam[2],
            pnp_size_200_cam[0],
            pnp_size_200_cam[1],
            pnp_size_200_cam[2],
            pnp_size_210_cam[0],
            pnp_size_210_cam[1],
            pnp_size_210_cam[2],
            pnp_size_190_world[0],
            pnp_size_190_world[1],
            pnp_size_190_world[2],
            pnp_size_200_world[0],
            pnp_size_200_world[1],
            pnp_size_200_world[2],
            pnp_size_210_world[0],
            pnp_size_210_world[1],
            pnp_size_210_world[2],
            pnp_size_190_reproj_error,
            pnp_size_200_reproj_error,
            pnp_size_210_reproj_error,
            pnp_size_190_gt_error,
            pnp_size_200_gt_error,
            pnp_size_210_gt_error,
            pnp_solver_used,
            live_solver_name,
            live_solver_world[0],
            live_solver_world[1],
            live_solver_world[2],
            live_solver_reproj_error,
            ippe_world_error_gt,
            iterative_world_error_gt,
            pnp_fallback_reason,
            pnp_best_debug_solver,
            pnp_best_debug_order,
            pnp_current_world_error_gt,
            pnp_best_world_error_gt,
            pnp_current_cam[0],
            pnp_current_cam[1],
            pnp_current_cam[2],
            pnp_best_cam[0],
            pnp_best_cam[1],
            pnp_best_cam[2],
            pnp_current_world[0],
            pnp_current_world[1],
            pnp_current_world[2],
            pnp_best_world[0],
            pnp_best_world[1],
            pnp_best_world[2],
            pnp_current_reproj_error,
            pnp_best_reproj_error,
            pnp_candidate0_world[0],
            pnp_candidate0_world[1],
            pnp_candidate0_world[2],
            pnp_candidate1_world[0],
            pnp_candidate1_world[1],
            pnp_candidate1_world[2],
            pnp_candidate0_error,
            pnp_candidate1_error,
            pnp_gt_projected_center[0],
            pnp_gt_projected_center[1],
            pnp_gt_projected_quad_center_error_px,
        ])

        self.log_file.flush()

        self.last_t = now
        self.last_vel = vel.copy()

    def close(self):
        self.log_file.close()
