import csv
import time
import math
import numpy as np


class FlightLogger:
    def __init__(self, filename="flight_log.csv"):
        self.log_file = open(filename, "w", newline="")
        self.writer = csv.writer(self.log_file)

        self.writer.writerow([
            "t",

            # Actual drone state
            "px", "py", "pz",
            "vx", "vy", "vz",
            "ax", "ay", "az",

            # Commanded attitude/thrust
            "roll_cmd_deg",
            "pitch_cmd_deg",
            "yaw_cmd_deg",
            "thrust_cmd",

            # Planner reference
            "p_ref_x", "p_ref_y", "p_ref_z",
            "v_ref_x", "v_ref_y", "v_ref_z",
            "a_ref_x", "a_ref_y", "a_ref_z",

            # Target gate / waypoint
            "target_x", "target_y", "target_z",

            # Debug info
            "tracking_err_x",
            "tracking_err_y",
            "tracking_err_z",
            "tracking_err_norm",
            "mode",
            "active_gate_idx",
            "loop_dt",
            "replan_requested",
            "replan_duration",
            "hold_command",
            "stale_command_suppressed",
            "plan_mode",
            "plan_start_gate_idx",
            "plan_end_gate_idx",
            "raw_gate_x",
            "raw_gate_y",
            "raw_gate_z",
            "perception_accepted",
            "perception_rejection_reason",
            "last_valid_target_x",
            "last_valid_target_y",
            "last_valid_target_z",
            "target_z_clamped",
            "perception_replan_trigger",
            "distance_to_active_target",
            "gate_completion_triggered",
            "completion_reason",
            "completed_gate_x",
            "completed_gate_y",
            "completed_gate_z",
            "active_gate_idx_before",
            "active_gate_idx_after",
            "race_cursor_before",
            "race_cursor_after",
            "active_target_source",
            "target_rejected_completed",
            "candidate_track_id",
            "candidate_x",
            "candidate_y",
            "candidate_z",
            "candidate_order_score",
            "rejected_wrong_order",
            "rejected_duplicate",
            "rejected_completed_this_lap",
            "race_cursor_advanced",
            "active_gate_idx_advanced",
            "completed_landmark_count",
            "lap_reset_triggered",
            "active_target_cleared",
            "active_target_track_id",
            "completed_gate_track_id",
            "yaw_target_source",
            "target_retained_after_completion",
            "next_valid_target_found",
            "valid_candidate_count",
            "approach_vector_x",
            "approach_vector_y",
            "approach_vector_z",
            "gate_progress_along_approach",
            "gate_lateral_error",
            "gate_plane_crossed",
            "near_gate_but_not_crossed",
            "completion_blocked_reason",
            "no_active_target",
            "no_target_control_mode",
            "hold_anchor_source",
            "hold_anchor_x",
            "hold_anchor_y",
            "hold_anchor_z",
            "velocity_damping_active",
            "completed_gate_reference_blocked",
            "p_ref_source",
            "yaw_hold_value",
            "telemetry_yaw_deg",
            "previous_yaw_cmd_deg",
            "raw_yaw_cmd_deg",
            "yaw_cmd_after_unwrap_deg",
            "yaw_rate_limited",
            "post_completion_grace_active",
            "no_target_roll_source",
            "no_target_pitch_source",
            "horizontal_hold_disabled_after_completion",
            "track_id",
            "merged_into_track_id",
            "duplicate_merge_reason",
            "race_order_track_ids",
            "race_order_inserted",
            "race_order_rejected_reason",
            "landmark_uncertainty",
            "track_observations",
            "completed_unique_gate_count",
            "active_gate_idx_clamped_by_race_gate_count",
            "suspected_duplicate_track",
            "committed_track_centers",
            "pairwise_committed_track_distances",
            "duplicate_radius_used",
            "merge_candidate_pairs",
            "merge_blocked_reason",
            "rejected_track_temporary_vs_permanent",
            "active_target_admission_status",
            "race_order_after_merge",
            "raw_image_corners",
            "ordered_image_corners",
            "pnp_rvec_x",
            "pnp_rvec_y",
            "pnp_rvec_z",
            "pnp_tvec_x",
            "pnp_tvec_y",
            "pnp_tvec_z",
            "gate_center_camera_x",
            "gate_center_camera_y",
            "gate_center_camera_z",
            "gate_center_body_x",
            "gate_center_body_y",
            "gate_center_body_z",
            "gate_center_world_x",
            "gate_center_world_y",
            "gate_center_world_z",
            "gate_normal_world_x",
            "gate_normal_world_y",
            "gate_normal_world_z",
            "detection_drone_x",
            "detection_drone_y",
            "detection_drone_z",
            "detection_drone_roll_rad",
            "detection_drone_pitch_rad",
            "detection_drone_yaw_rad",
            "reprojection_error",
            "image_width",
            "image_height",
            "min_corner_x",
            "max_corner_x",
            "min_corner_y",
            "max_corner_y",
            "corner_margin_ok",
            "clipped_detection_rejected",
            "rejected_near_image_edge",
            "track_update_innovation",
            "track_update_accepted",
            "track_center_before_x",
            "track_center_before_y",
            "track_center_before_z",
            "track_center_after_x",
            "track_center_after_y",
            "track_center_after_z",
            "raw_corner_0_x",
            "raw_corner_0_y",
            "raw_corner_1_x",
            "raw_corner_1_y",
            "raw_corner_2_x",
            "raw_corner_2_y",
            "raw_corner_3_x",
            "raw_corner_3_y",
            "ordered_corner_0_x",
            "ordered_corner_0_y",
            "ordered_corner_1_x",
            "ordered_corner_1_y",
            "ordered_corner_2_x",
            "ordered_corner_2_y",
            "ordered_corner_3_x",
            "ordered_corner_3_y",
            "reprojected_corner_0_x",
            "reprojected_corner_0_y",
            "reprojected_corner_1_x",
            "reprojected_corner_1_y",
            "reprojected_corner_2_x",
            "reprojected_corner_2_y",
            "reprojected_corner_3_x",
            "reprojected_corner_3_y",
            "corner_reprojection_error_px",
            "quad_center_x",
            "quad_center_y",
            "image_center_x",
            "image_center_y",
            "quad_center_offset_x",
            "quad_center_offset_y",
            "quad_width_px",
            "quad_height_px",
            "quad_aspect_ratio",
            "quad_area_px",
            "pnp_candidate_count",
            "chosen_pnp_candidate",
            "pnp_candidate_0_error",
            "pnp_candidate_1_error",
            "gate_normal_camera_x",
            "gate_normal_camera_y",
            "gate_normal_camera_z",
            "gate_cam_x",
            "gate_cam_y",
            "gate_cam_z",
            "gate_body_x",
            "gate_body_y",
            "gate_body_z",
            "gate_world_x",
            "gate_world_y",
            "gate_world_z",
            "drone_x_at_detection",
            "drone_y_at_detection",
            "drone_z_at_detection",
            "drone_roll_at_detection_deg",
            "drone_pitch_at_detection_deg",
            "drone_yaw_at_detection_deg",
            "transform_source",
            "camera_to_body_matrix_used",
            "body_to_world_method_used",
            "expected_gate_cam_x",
            "expected_gate_cam_y",
            "expected_gate_cam_z",
            "pnp_gate_cam_x",
            "pnp_gate_cam_y",
            "pnp_gate_cam_z",
            "camera_error_x",
            "camera_error_y",
            "camera_error_z",
            "camera_error_norm",
            "expected_gate_body_x",
            "expected_gate_body_y",
            "expected_gate_body_z",
            "pnp_gate_body_x",
            "pnp_gate_body_y",
            "pnp_gate_body_z",
            "body_error_x",
            "body_error_y",
            "body_error_z",
            "expected_gate_world_x",
            "expected_gate_world_y",
            "expected_gate_world_z",
            "pnp_gate_world_x",
            "pnp_gate_world_y",
            "pnp_gate_world_z",
            "world_error_x",
            "world_error_y",
            "world_error_z",
            "world_error_norm",
            "pnp_size_190_cam_x",
            "pnp_size_190_cam_y",
            "pnp_size_190_cam_z",
            "pnp_size_200_cam_x",
            "pnp_size_200_cam_y",
            "pnp_size_200_cam_z",
            "pnp_size_210_cam_x",
            "pnp_size_210_cam_y",
            "pnp_size_210_cam_z",
            "pnp_size_190_world_x",
            "pnp_size_190_world_y",
            "pnp_size_190_world_z",
            "pnp_size_200_world_x",
            "pnp_size_200_world_y",
            "pnp_size_200_world_z",
            "pnp_size_210_world_x",
            "pnp_size_210_world_y",
            "pnp_size_210_world_z",
            "pnp_size_190_reproj_error",
            "pnp_size_200_reproj_error",
            "pnp_size_210_reproj_error",
            "pnp_size_190_gt_error",
            "pnp_size_200_gt_error",
            "pnp_size_210_gt_error",
        ])

        self.t0 = time.time()
        self.last_t = None
        self.last_vel = None

    def _vec3(self, value):
        """
        Converts list/tuple/np.array/dict/None into a 3-value numpy vector.
        Returns [nan, nan, nan] if unavailable.
        """
        if value is None:
            return np.array([np.nan, np.nan, np.nan], dtype=float)

        if isinstance(value, dict):
            # Supports {"x":..., "y":..., "z":...}
            if all(k in value for k in ["x", "y", "z"]):
                return np.array([value["x"], value["y"], value["z"]], dtype=float)

            # Supports {"north":..., "east":..., "up":...}
            if all(k in value for k in ["north", "east", "up"]):
                return np.array([value["north"], value["east"], value["up"]], dtype=float)

            return np.array([np.nan, np.nan, np.nan], dtype=float)

        arr = np.array(value, dtype=float).reshape(-1)

        if arr.size >= 3:
            return arr[:3]

        return np.array([np.nan, np.nan, np.nan], dtype=float)

    def _flat_string(self, value):
        if value is None:
            return ""
        arr = np.asarray(value, dtype=float).reshape(-1)
        return " ".join(f"{x:.3f}" for x in arr)

    def _corners4(self, value):
        out = np.full((4, 2), np.nan, dtype=float)
        if value is None:
            return out
        try:
            arr = np.asarray(value, dtype=float).reshape(-1, 2)
        except Exception:
            return out
        n = min(4, arr.shape[0])
        if n > 0:
            out[:n, :] = arr[:n, :]
        return out

    def log(
        self,
        telemetry,
        roll_cmd,
        pitch_cmd,
        yaw_cmd,
        thrust_cmd,
        p_ref=None,
        v_ref=None,
        a_ref=None,
        target=None,
        mode=None,
        active_gate_idx=None,
        loop_dt=np.nan,
        replan_requested=False,
        replan_duration=0.0,
        hold_command=False,
        stale_command_suppressed=False,
        plan_mode=None,
        plan_start_gate_idx=None,
        plan_end_gate_idx=None,
        raw_gate=None,
        perception_accepted=False,
        perception_rejection_reason="",
        last_valid_target=None,
        target_z_clamped=False,
        perception_replan_trigger=False,
        distance_to_active_target=np.nan,
        gate_completion_triggered=False,
        completion_reason="",
        completed_gate_position=None,
        active_gate_idx_before=None,
        active_gate_idx_after=None,
        race_cursor_before=None,
        race_cursor_after=None,
        active_target_source="",
        target_rejected_completed=False,
        candidate_track_id=None,
        candidate_center=None,
        candidate_order_score=np.nan,
        rejected_wrong_order=False,
        rejected_duplicate=False,
        rejected_completed_this_lap=False,
        race_cursor_advanced=False,
        active_gate_idx_advanced=False,
        completed_landmark_count=0,
        lap_reset_triggered=False,
        active_target_cleared=False,
        active_target_track_id=None,
        completed_gate_track_id=None,
        yaw_target_source="",
        target_retained_after_completion=False,
        next_valid_target_found=False,
        valid_candidate_count=0,
        approach_vector=None,
        gate_progress_along_approach=np.nan,
        gate_lateral_error=np.nan,
        gate_plane_crossed=False,
        near_gate_but_not_crossed=False,
        completion_blocked_reason="",
        no_active_target=False,
        no_target_control_mode="",
        hold_anchor_source="",
        hold_anchor=None,
        velocity_damping_active=False,
        completed_gate_reference_blocked=False,
        p_ref_source="",
        yaw_hold_value=np.nan,
        telemetry_yaw_deg=np.nan,
        previous_yaw_cmd_deg=np.nan,
        raw_yaw_cmd_deg=np.nan,
        yaw_cmd_after_unwrap_deg=np.nan,
        yaw_rate_limited=False,
        post_completion_grace_active=False,
        no_target_roll_source="",
        no_target_pitch_source="",
        horizontal_hold_disabled_after_completion=False,
        track_id=None,
        merged_into_track_id=None,
        duplicate_merge_reason="",
        race_order_track_ids=None,
        race_order_inserted=False,
        race_order_rejected_reason="",
        landmark_uncertainty=np.nan,
        track_observations=0,
        completed_unique_gate_count=0,
        active_gate_idx_clamped_by_race_gate_count=False,
        suspected_duplicate_track=False,
        committed_track_centers="",
        pairwise_committed_track_distances="",
        duplicate_radius_used=np.nan,
        merge_candidate_pairs="",
        merge_blocked_reason="",
        rejected_track_temporary_vs_permanent="",
        active_target_admission_status="",
        race_order_after_merge=None,
        raw_image_corners=None,
        ordered_image_corners=None,
        pnp_rvec=None,
        pnp_tvec=None,
        gate_center_camera=None,
        gate_center_body=None,
        gate_center_world_debug=None,
        gate_normal_world=None,
        gate_normal_camera=None,
        detection_drone_pose=None,
        reprojection_error=np.nan,
        reprojected_corners=None,
        corner_reprojection_error_px=np.nan,
        quad_center_x=np.nan,
        quad_center_y=np.nan,
        image_center_x=np.nan,
        image_center_y=np.nan,
        quad_center_offset_x=np.nan,
        quad_center_offset_y=np.nan,
        quad_width_px=np.nan,
        quad_height_px=np.nan,
        quad_aspect_ratio=np.nan,
        quad_area_px=np.nan,
        pnp_candidate_count=0,
        chosen_pnp_candidate=None,
        pnp_candidate_0_error=np.nan,
        pnp_candidate_1_error=np.nan,
        transform_source="",
        camera_to_body_matrix_used=None,
        body_to_world_method_used="",
        expected_gate_cam=None,
        pnp_gate_cam=None,
        camera_error=None,
        camera_error_norm=np.nan,
        expected_gate_body=None,
        pnp_gate_body=None,
        body_error=None,
        expected_gate_world=None,
        pnp_gate_world=None,
        world_error=None,
        world_error_norm=np.nan,
        pnp_size_190_cam=None,
        pnp_size_200_cam=None,
        pnp_size_210_cam=None,
        pnp_size_190_world=None,
        pnp_size_200_world=None,
        pnp_size_210_world=None,
        pnp_size_190_reproj_error=np.nan,
        pnp_size_200_reproj_error=np.nan,
        pnp_size_210_reproj_error=np.nan,
        pnp_size_190_gt_error=np.nan,
        pnp_size_200_gt_error=np.nan,
        pnp_size_210_gt_error=np.nan,
        image_width=0,
        image_height=0,
        min_corner_x=np.nan,
        max_corner_x=np.nan,
        min_corner_y=np.nan,
        max_corner_y=np.nan,
        corner_margin_ok=False,
        clipped_detection_rejected=False,
        rejected_near_image_edge=False,
        track_update_innovation=np.nan,
        track_update_accepted=False,
        track_center_before_update=None,
        track_center_after_update=None,
    ):
        now = time.time()
        t = now - self.t0

        # Your GetTelemetry seems to store pos/vel as dicts
        pos = self._vec3(getattr(telemetry, "pos", None))
        vel = self._vec3(getattr(telemetry, "vel", None))

        if self.last_t is None or self.last_vel is None:
            acc = np.array([0.0, 0.0, 0.0])
        else:
            dt = now - self.last_t
            acc = (vel - self.last_vel) / dt if dt > 1e-6 else np.zeros(3)

        p_ref = self._vec3(p_ref)
        v_ref = self._vec3(v_ref)
        a_ref = self._vec3(a_ref)
        target = self._vec3(target)
        raw_gate = self._vec3(raw_gate)
        last_valid_target = self._vec3(last_valid_target)
        completed_gate_position = self._vec3(completed_gate_position)
        candidate_center = self._vec3(candidate_center)
        approach_vector = self._vec3(approach_vector)
        hold_anchor = self._vec3(hold_anchor)
        pnp_rvec = self._vec3(pnp_rvec)
        pnp_tvec = self._vec3(pnp_tvec)
        gate_center_camera = self._vec3(gate_center_camera)
        gate_center_body = self._vec3(gate_center_body)
        gate_center_world_debug = self._vec3(gate_center_world_debug)
        gate_normal_world = self._vec3(gate_normal_world)
        gate_normal_camera = self._vec3(gate_normal_camera)
        track_center_before_update = self._vec3(track_center_before_update)
        track_center_after_update = self._vec3(track_center_after_update)
        expected_gate_cam = self._vec3(expected_gate_cam)
        pnp_gate_cam = self._vec3(pnp_gate_cam)
        camera_error = self._vec3(camera_error)
        expected_gate_body = self._vec3(expected_gate_body)
        pnp_gate_body = self._vec3(pnp_gate_body)
        body_error = self._vec3(body_error)
        expected_gate_world = self._vec3(expected_gate_world)
        pnp_gate_world = self._vec3(pnp_gate_world)
        world_error = self._vec3(world_error)
        pnp_size_190_cam = self._vec3(pnp_size_190_cam)
        pnp_size_200_cam = self._vec3(pnp_size_200_cam)
        pnp_size_210_cam = self._vec3(pnp_size_210_cam)
        pnp_size_190_world = self._vec3(pnp_size_190_world)
        pnp_size_200_world = self._vec3(pnp_size_200_world)
        pnp_size_210_world = self._vec3(pnp_size_210_world)
        raw_corners = self._corners4(raw_image_corners)
        ordered_corners = self._corners4(ordered_image_corners)
        reprojected_corners = self._corners4(reprojected_corners)
        detection_pose = np.asarray(detection_drone_pose, dtype=float).reshape(-1) if detection_drone_pose is not None else np.full(6, np.nan)
        if detection_pose.size < 6:
            detection_pose = np.full(6, np.nan)
        chosen_pnp_candidate = -1 if chosen_pnp_candidate is None else chosen_pnp_candidate

        err = p_ref - pos
        err_norm = float(np.linalg.norm(err)) if not np.any(np.isnan(err)) else np.nan

        self.writer.writerow([
            t,

            pos[0], pos[1], pos[2],
            vel[0], vel[1], vel[2],
            acc[0], acc[1], acc[2],

            math.degrees(roll_cmd),
            math.degrees(pitch_cmd),
            math.degrees(yaw_cmd),
            thrust_cmd,

            p_ref[0], p_ref[1], p_ref[2],
            v_ref[0], v_ref[1], v_ref[2],
            a_ref[0], a_ref[1], a_ref[2],

            target[0], target[1], target[2],

            err[0], err[1], err[2],
            err_norm,
            mode,
            active_gate_idx,
            loop_dt,
            bool(replan_requested),
            replan_duration,
            bool(hold_command),
            bool(stale_command_suppressed),
            plan_mode,
            plan_start_gate_idx,
            plan_end_gate_idx,
            raw_gate[0],
            raw_gate[1],
            raw_gate[2],
            bool(perception_accepted),
            perception_rejection_reason,
            last_valid_target[0],
            last_valid_target[1],
            last_valid_target[2],
            bool(target_z_clamped),
            bool(perception_replan_trigger),
            distance_to_active_target,
            bool(gate_completion_triggered),
            completion_reason,
            completed_gate_position[0],
            completed_gate_position[1],
            completed_gate_position[2],
            active_gate_idx_before,
            active_gate_idx_after,
            race_cursor_before,
            race_cursor_after,
            active_target_source,
            bool(target_rejected_completed),
            candidate_track_id,
            candidate_center[0],
            candidate_center[1],
            candidate_center[2],
            candidate_order_score,
            bool(rejected_wrong_order),
            bool(rejected_duplicate),
            bool(rejected_completed_this_lap),
            bool(race_cursor_advanced),
            bool(active_gate_idx_advanced),
            completed_landmark_count,
            bool(lap_reset_triggered),
            bool(active_target_cleared),
            active_target_track_id,
            completed_gate_track_id,
            yaw_target_source,
            bool(target_retained_after_completion),
            bool(next_valid_target_found),
            valid_candidate_count,
            approach_vector[0],
            approach_vector[1],
            approach_vector[2],
            gate_progress_along_approach,
            gate_lateral_error,
            bool(gate_plane_crossed),
            bool(near_gate_but_not_crossed),
            completion_blocked_reason,
            bool(no_active_target),
            no_target_control_mode,
            hold_anchor_source,
            hold_anchor[0],
            hold_anchor[1],
            hold_anchor[2],
            bool(velocity_damping_active),
            bool(completed_gate_reference_blocked),
            p_ref_source,
            yaw_hold_value,
            telemetry_yaw_deg,
            previous_yaw_cmd_deg,
            raw_yaw_cmd_deg,
            yaw_cmd_after_unwrap_deg,
            bool(yaw_rate_limited),
            bool(post_completion_grace_active),
            no_target_roll_source,
            no_target_pitch_source,
            bool(horizontal_hold_disabled_after_completion),
            track_id,
            merged_into_track_id,
            duplicate_merge_reason,
            "" if race_order_track_ids is None else " ".join(str(x) for x in race_order_track_ids),
            bool(race_order_inserted),
            race_order_rejected_reason,
            landmark_uncertainty,
            track_observations,
            completed_unique_gate_count,
            bool(active_gate_idx_clamped_by_race_gate_count),
            bool(suspected_duplicate_track),
            committed_track_centers,
            pairwise_committed_track_distances,
            duplicate_radius_used,
            merge_candidate_pairs,
            merge_blocked_reason,
            rejected_track_temporary_vs_permanent,
            active_target_admission_status,
            "" if race_order_after_merge is None else " ".join(str(x) for x in race_order_after_merge),
            self._flat_string(raw_image_corners),
            self._flat_string(ordered_image_corners),
            pnp_rvec[0],
            pnp_rvec[1],
            pnp_rvec[2],
            pnp_tvec[0],
            pnp_tvec[1],
            pnp_tvec[2],
            gate_center_camera[0],
            gate_center_camera[1],
            gate_center_camera[2],
            gate_center_body[0],
            gate_center_body[1],
            gate_center_body[2],
            gate_center_world_debug[0],
            gate_center_world_debug[1],
            gate_center_world_debug[2],
            gate_normal_world[0],
            gate_normal_world[1],
            gate_normal_world[2],
            detection_pose[0],
            detection_pose[1],
            detection_pose[2],
            detection_pose[3],
            detection_pose[4],
            detection_pose[5],
            reprojection_error,
            image_width,
            image_height,
            min_corner_x,
            max_corner_x,
            min_corner_y,
            max_corner_y,
            bool(corner_margin_ok),
            bool(clipped_detection_rejected),
            bool(rejected_near_image_edge),
            track_update_innovation,
            bool(track_update_accepted),
            track_center_before_update[0],
            track_center_before_update[1],
            track_center_before_update[2],
            track_center_after_update[0],
            track_center_after_update[1],
            track_center_after_update[2],
            raw_corners[0, 0],
            raw_corners[0, 1],
            raw_corners[1, 0],
            raw_corners[1, 1],
            raw_corners[2, 0],
            raw_corners[2, 1],
            raw_corners[3, 0],
            raw_corners[3, 1],
            ordered_corners[0, 0],
            ordered_corners[0, 1],
            ordered_corners[1, 0],
            ordered_corners[1, 1],
            ordered_corners[2, 0],
            ordered_corners[2, 1],
            ordered_corners[3, 0],
            ordered_corners[3, 1],
            reprojected_corners[0, 0],
            reprojected_corners[0, 1],
            reprojected_corners[1, 0],
            reprojected_corners[1, 1],
            reprojected_corners[2, 0],
            reprojected_corners[2, 1],
            reprojected_corners[3, 0],
            reprojected_corners[3, 1],
            corner_reprojection_error_px,
            quad_center_x,
            quad_center_y,
            image_center_x,
            image_center_y,
            quad_center_offset_x,
            quad_center_offset_y,
            quad_width_px,
            quad_height_px,
            quad_aspect_ratio,
            quad_area_px,
            pnp_candidate_count,
            chosen_pnp_candidate,
            pnp_candidate_0_error,
            pnp_candidate_1_error,
            gate_normal_camera[0],
            gate_normal_camera[1],
            gate_normal_camera[2],
            gate_center_camera[0],
            gate_center_camera[1],
            gate_center_camera[2],
            gate_center_body[0],
            gate_center_body[1],
            gate_center_body[2],
            gate_center_world_debug[0],
            gate_center_world_debug[1],
            gate_center_world_debug[2],
            detection_pose[0],
            detection_pose[1],
            detection_pose[2],
            math.degrees(detection_pose[3]),
            math.degrees(detection_pose[4]),
            math.degrees(detection_pose[5]),
            transform_source,
            self._flat_string(camera_to_body_matrix_used),
            body_to_world_method_used,
            expected_gate_cam[0],
            expected_gate_cam[1],
            expected_gate_cam[2],
            pnp_gate_cam[0],
            pnp_gate_cam[1],
            pnp_gate_cam[2],
            camera_error[0],
            camera_error[1],
            camera_error[2],
            camera_error_norm,
            expected_gate_body[0],
            expected_gate_body[1],
            expected_gate_body[2],
            pnp_gate_body[0],
            pnp_gate_body[1],
            pnp_gate_body[2],
            body_error[0],
            body_error[1],
            body_error[2],
            expected_gate_world[0],
            expected_gate_world[1],
            expected_gate_world[2],
            pnp_gate_world[0],
            pnp_gate_world[1],
            pnp_gate_world[2],
            world_error[0],
            world_error[1],
            world_error[2],
            world_error_norm,
            pnp_size_190_cam[0],
            pnp_size_190_cam[1],
            pnp_size_190_cam[2],
            pnp_size_200_cam[0],
            pnp_size_200_cam[1],
            pnp_size_200_cam[2],
            pnp_size_210_cam[0],
            pnp_size_210_cam[1],
            pnp_size_210_cam[2],
            pnp_size_190_world[0],
            pnp_size_190_world[1],
            pnp_size_190_world[2],
            pnp_size_200_world[0],
            pnp_size_200_world[1],
            pnp_size_200_world[2],
            pnp_size_210_world[0],
            pnp_size_210_world[1],
            pnp_size_210_world[2],
            pnp_size_190_reproj_error,
            pnp_size_200_reproj_error,
            pnp_size_210_reproj_error,
            pnp_size_190_gt_error,
            pnp_size_200_gt_error,
            pnp_size_210_gt_error,
        ])

        self.log_file.flush()

        self.last_t = now
        self.last_vel = vel.copy()

    def close(self):
        self.log_file.close()
